apiVersion: batch/v1
kind: Job
metadata:
  name: ajob
spec:
  template:
    spec:
      containers:
        - name: acontainer
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - date; echo Hello!; sleep 40s
      restartPolicy: OnFailure