apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .;../env-prod
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: { }
  source:
    chart: appchart
    repoURL: https://github.com/thober35/argocd-path-issue.git
    path: appchart
    targetRevision: HEAD
    helm:
      releaseName: app-env-dev
      valueFiles:
        - ../env-dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: env-dev