apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - namespace: env-dev-set
        value: env-dev
        path: ".;../env-all"
        rolloutWave: "1"
      - namespace: env-prod-set
        value: env-prod
        path: "."
        rolloutWave: "2"
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: rolloutWave
              operator: In
              values:
                - "1"
        - matchExpressions:
            - key: rolloutWave
              operator: In
              values:
                - "2"
  template:
    metadata:
      name: '{{namespace}}-guestbook'
      labels:
        rolloutWave: "{{`{{rolloutWave}}`}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: '{{path}}'
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated: { }
      source:
        repoURL: https://github.com/thober35/argocd-path-issue
        path: appchart
        targetRevision: HEAD
        helm:
          valueFiles:
            - '../{{value}}/values.yaml'
            - ../env-all/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
